### ISSUE TITLE
قیمت کل به بیت‌کوین- سبدخرید- 

### ISSUE THREAD

**Issue by NimaArnar** [zakiye-zand/AP-Project-2#5]
قیمت کل داخل سبد خرید به بیت‌کوین باید نمایش داده بشه
ساختار سبد خرید مشکل داره و با فرانت ارتباط برقرار نمیکنه
چندتا از لیست‌های تعریف شده اشتباهه و متود و تابعش باید اصلاح بشه.

def removeFromeCart():
    productId = int(request.args.get("productId"))

اینجا بهتره از form استفاده شه.

**Comment by zakiye-zand** [comment]
اوکی ، درست شد
